# Generated by Django 6.0.2 on 2026-02-10 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_client_assigned_to_alter_lead_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
