# Generated by Django 6.0.2 on 2026-02-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_client_assigned_to_client_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_follow_up',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('COLD', 'Cold (Just Started)'), ('WARM', 'Warm (Interested)'), ('HOT', 'Hot (Ready to Close)'), ('CONVERTED', 'Converted to Client')], default='COLD', max_length=20),
        ),
    ]
