# Generated by Django 6.0.2 on 2026-02-20 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_document_lead_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Select the 1st day of the target month', verbose_name='Month')),
                ('target_leads', models.IntegerField(default=0, verbose_name='Target: Leads Converted')),
                ('target_tasks', models.IntegerField(default=0, verbose_name='Target: Tasks Completed')),
                ('target_interactions', models.IntegerField(default=0, verbose_name='Target: Interactions')),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Target: Revenue (৳)')),
                ('notes', models.TextField(blank=True, verbose_name='Manager Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets_created', to=settings.AUTH_USER_MODEL, verbose_name='Set By')),
                ('staff', models.ForeignKey(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'KPI Target',
                'verbose_name_plural': 'KPI Targets',
                'ordering': ['-month', 'staff'],
                'unique_together': {('staff', 'month')},
            },
        ),
    ]
