# Generated by Django 6.0.2 on 2026-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_kpi_target_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Converted At'),
        ),
    ]
